# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('publication_date', models.DateField(null=True)),
                ('developer', models.CharField(blank=True, max_length=155, null=True)),
                ('image', models.FileField(upload_to='images/')),
                ('game_type', models.PositiveSmallIntegerField(choices=[(1, 'PS4'), (2, 'Xbox One'), (3, 'PC'), (4, 'Wii U'), (5, 'Mobile')])),
            ],
        ),
    ]
